export const images = [
  {
    src: "/images/odsutnost1.jpg",
    alt: "Odsutnost 1",
    name: "Odsutnost 1",
    dimensions: "61x98cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2  md:col-span-1 ",
    width: "w-full",
  },
  {
    src: "/images/bezNaziva1.jpg",
    alt: "Slika je bez naziva",
    dimensions: "15x11cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
    height: "h-[400px] md:h-[900px]",
  },
  {
    src: "/images/bezNaziva2.jpg",
    alt: "Slika je bez naziva",
    dimensions: "30x30cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
  },
  {
    src: "/images/odsutnost3.jpg",
    alt: "Odsutnost 3",
    name: "Odsutnost 3",
    dimensions: "70x100cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1",
  },
  {
    src: "/images/odsutnost2.jpg",
    alt: "Odsutnost 2",
    name: "Odsutnost 2",
    dimensions: "67x100cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1",
  },
  {
    src: "/images/oblaci.jpg",
    alt: "Oblaci",
    dimensions: "16x16cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-3",
  },
  {
    src: "/images/bezNaziva3.jpg",
    alt: "Slika je bez naziva",
    dimensions: "70x100cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1",
  },
  {
    src: "/images/bezNaziva4.jpg",
    alt: "Slika je bez naziva",
    dimensions: "100x70cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
  },
  {
    src: "/images/bezNaziva5.jpg",
    alt: "Slika je bez naziva",
    dimensions: "70x100cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
  },
  {
    src: "/images/bezNaziva6.jpg",
    alt: "Slika je bez naziva",
    dimensions: "25x25cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1",
  },
  {
    src: "/images/odsutnost4.jpg",
    alt: "Odustnost 4",
    name: "Odsutnost 4",
    dimensions: "33x35cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1",
  },
  {
    src: "/images/opiranje3.jpg",
    alt: "Opiranje 3",
    name: "Opiranje 3",
    dimensions: "150x100cm",
    technique: "Ulje na platnu",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
  },
  {
    src: "/images/odsutnost5.jpg",
    alt: "Odsutnost 5",
    name: "Odsutnost 5",
    dimensions: "70x100cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full",
  },
  {
    src: "/images/opiranje4.jpg",
    alt: "Opiranje 4",
    name: "Opiranje 4",
    dimensions: "150x100cm",
    technique: "Ulje na platnu",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full md:row-span-2",
  },
  {
    src: "/images/opiranje1.jpg",
    alt: "Opiranje 1",
    name: "Opiranje 1",
    dimensions: "80x130cm",
    technique: "Ulje na platnu",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full ",
  },
  {
    src: "/images/bezNaziva7.jpg",
    alt: "Slika je bez naziva",
    dimensions: "50x70cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full",
  },
  {
    src: "/images/bezNaziva8.jpg",
    alt: "Slika je bez naziva",
    dimensions: "55x75cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-[440px] md:row-span-1",
  },
  {
    src: "/images/bezNaziva9.jpg",
    alt: "Slika je bez naziva",
    dimensions: "45x81cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full md:row-span-2",
  },
  {
    src: "/images/bezNaziva.jpg",
    alt: "Slika je bez naziva",
    dimensions: "66x99cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-[440px] md:row-span-1",
  },
];
