export const images = [
  {
    src: "/images/bezNaziva10.jpg",
    alt: "Bez Naziva",
    name: "Bez Naziva",
    dimensions: "29x40cm",
    technique: "Grafit na papiru",
    grid: "col-span-2  md:col-span-1 ",
    width: "w-full",
  },
  {
    src: "/images/bezNaziva6.jpg",
    alt: "Slika je bez naziva",
    dimensions: "15x11cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
    height: "h-[400px] md:h-[900px]",
  },
  {
    src: "/images/bezNaziva2.jpg",
    name: "Bez Naziva",
    alt: "Slika je bez naziva",
    dimensions: "30x30cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
  },
  {
    src: "/images/odsutnost3.jpg",
    alt: "Odsutnost 3",
    name: "Odsutnost 3",
    dimensions: "70x100cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1",
  },
  {
    src: "/images/odsutnost2.jpg",
    alt: "Odsutnost 2",
    name: "Odsutnost 2",
    dimensions: "67x100cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1",
  },
  {
    src: "/images/oblaci.jpg",
    alt: "Oblaci",
    dimensions: "16x16cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2 ",
  },
  {
    src: "/images/bezNaziva3.jpg",
    alt: "Slika je bez naziva",
    dimensions: "70x100cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1",
  },
  {
    src: "/images/bezNaziva4.jpg",
    alt: "Slika je bez naziva",
    dimensions: "100x70cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
  },
  {
    src: "/images/bezNaziva5.jpg",
    alt: "Slika je bez naziva",
    dimensions: "70x100cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
  },
  {
    src: "/images/mementoMori.jpg",
    alt: "Slika je bez naziva",
    dimensions: "25x25cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1",
  },
  {
    src: "/images/odsutnost4.jpg",
    alt: "Odustnost 4",
    name: "Odsutnost 4",
    dimensions: "33x35cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 ",
  },
  {
    src: "/images/opiranje3.jpg",
    alt: "Opiranje 3",
    name: "Opiranje 3",
    dimensions: "150x100cm",
    technique: "Ulje na platnu",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-2",
  },
  {
    src: "/images/odsutnost5.jpg",
    alt: "Odsutnost 5",
    name: "Odsutnost 5",
    dimensions: "70x100cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full",
  },
  {
    src: "/images/opiranje4.jpg",
    alt: "Opiranje 4",
    name: "Opiranje 4",
    dimensions: "150x100cm",
    technique: "Ulje na platnu",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full md:row-span-2",
  },
  {
    src: "/images/opiranje1.jpg",
    alt: "Opiranje 1",
    name: "Opiranje 1",
    dimensions: "80x130cm",
    technique: "Ulje na platnu",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full ",
  },
  {
    src: "/images/bezNaziva7.jpg",
    alt: "Slika je bez naziva",
    dimensions: "50x70cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full",
  },
  {
    src: "/images/bezNaziva8.jpg",
    alt: "Slika je bez naziva",
    dimensions: "55x75cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-[440px] md:row-span-1",
  },
  {
    src: "/images/bezNaziva9.jpg",
    alt: "Slika je bez naziva",
    dimensions: "45x81cm",
    technique: "Grafit na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-full md:row-span-2",
  },
  {
    src: "/images/bezNaziva.jpg",
    alt: "Slika je bez naziva",
    dimensions: "66x99cm",
    technique: "Grafitna olovka na papiru",
    grid: "col-span-2 row-span-1 md:col-span-1 md:row-span-1 h-[400px] md:h-[440px] md:row-span-1",
  },
];

export const imagesAtelje = [
  {
    src: "/images/ateljeImg.jpg",
    alt: "Slika ucionice za crtanje",
  },
  {
    src: "/images/ateljeImg1.jpg",
    alt: "Slika ucionice za crtanje",
  },
  {
    src: "/images/ateljeImg2.jpg",
    alt: "Slika ucionice za crtanje",
  },
  {
    src: "/images/ateljeImg3.jpg",
    alt: "Slika ucionice za crtanje",
  },
];

export const exhibitionsData = [
  {
    title: "Kolektivne izložbe",
    exhibitions: [
      "Godišnja izložba studentskih radova Akademije umjetnosti u Banjoj Luci, 2018, 2019, 2020, i 2021.",
      "„Tjelovitost“, Art klub Prostor, Banja Luka, 2018.",
      "„Ćilimi“, Filozofski fakultet, Banja Luka, 2019.",
      "„Multiverzumi I“, galerija „Djura Jakšić“, Filološki fakultet, Banja Luka, 2020.",
      "Izložba radova studenata Metodike likovnog vaspitanja, Filozofski fakultet, Banja Luka, 2020.",
      "„Multiverzumi II“, galerija Rektorata, Banja Luka, 2021.",
      "„Narodni vez“, Filozofski fakultet, Banja Luka, 2021.",
      "„Ćilimi i vez“, Vijećnica, Novi Grad, 2021.",
      "„Lasta 2021”, Ljetnja bašta JU „Centar za kulturu i obrazovanje”, Laktaši, 2021.",
      "Izložba radova studenata Psihologije stvaralaštva, Filozofski fakultet, Banja Luka, 2022.",
      "22. Krajiški likovni salon, Galerija ´73, Beograd, 2022.",
      "„Masterpieces IV“, Umjetnički prostor U10, Beograd, 2022.",
      "„Pogledi 2022.“, Galerija ´73, Beograd, 2022.",
      "„How to succeed in life“, Galerija Šira, Zagreb, 2022.",
      "„Lasta 2021”, Galerija JU „Centar za kulturu i obrazovanje”, Laktaši, 2022.",
      "Godišnja izložba studentskih radova Fakulteta likovnih umetnosti, Beograd, 2022.",
      "Izložba radova nagrađenih studenata Fakulteta likovnih umetnosti za 2021/2022. godinu, Galerija Fakulteta likovnih umetnosti, Beograd, 2022.",
      "14. Bijeljinski likovni salon, Galerija Centra za kulturu, Bijelijna, 2022.",
      "„Pogledi 2022.“, Galerija SKUC, Pula, 2022.",
      "ALU Perspektiva 2, Izložba „Petolik“, Akademija likovnih umjetnosti, Zagreb, 2022.",
      "„Inter/Akcija 2022“, Kamena kuća, Banja Luka, 2022.",
      "„Inter/Akcija 2022“, Kuća legata, Beograd, 2022.",
      "BPM 2023: Foto Bazaar, Galerija KVART, Beograd, 2023.",
      "„BečBijeljina“, Galerija Centra za kulturu, Bijeljina, 2023.",
      "II Međunarodna likovna kolonija „Banja Dvorovi 2023“, Galerija biblioteke „Filip Višnjić“, Bijeljina, 2023.",
      "15. Bijeljinski likovni salon, Galerija Centra za kulturu, Bijelijna, 2023.",
      "32. Izložba malog formata, Galerija kulturnog centra, Šabac, 2023.",
      "„BečBijeljina“, Vienna Design Week, Beč, 2023.",
      "23. Krajiški likovni salon, Konak knjeginje Ljubice, Beograd, 2023.",
      "31. izložba crteža, Galerija kulturnog centra, Šabac, 2024.",
    ],
  },
];

export const awardsData = [
  {
    title: "Nagrade",
    awards: [
      "Nagrada Akademije umjetnosti Univerziteta u Banjoj Luci za Studiju-crtež, 2018.",
      "Nagrada Akademije umjetnosti Univerziteta u Banjoj Luci za Studiju-sliku, 2019.",
      "Nagrada Art klub Prostora za najbolji rad iz medija crtež, 2019.",
      "Nagrada Zavičajnog muzeja Gradiška nagrada za slikarstvo (samostalna izložba), 2020.",
      "Nagrada „Galerije Sreten Stojanović“ (samostalna izložba), 2021.",
      "Nagrada Akademije umjetnosti Univerziteta u Banjoj Luci za Slikarstvo, 2021.",
      "Nagrada Muzeja savremene umjetnosti Republike Srpske (samostalna izložba), 2021.",
      "Nagrada Fakulteta likovnih umetnosti u Beogradu za crtež „Stevan Knežević“, 2022.",
    ],
  },
];

export const soloExhibitionsData = [
  {
    title: "Samostalne izložbe",
    exhibitions: [
      "„Odsutnost“, Art klub Prostor, Banja Luka, 2019.",
      "„Svjedoci Vremenu“, JU Zavičajni muzej Gradiška, 2021.",
      "„Svjedoci Vremenu“, Galerija „Sreten Stojanović“, Prijedor, 2022.",
      "„Prostor izvan svijeta“, Galerija Plus, Banja Luka, 2022.",
      "„Biti u Kronovoj utrobi“, Galerija Centra za kulturu „Semberija“, Bijeljina, 2023.",
      "„Bez naziva“, Galerija „Kvaka 22“, Beograd, 2023.",
    ],
  },
];
